export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
export const SEARCH_FETCH_USERS = 'SEARCH_FETCH_USERS';
export const SEARCH_SET_USERS = 'SEARCH_SET_USERS';
export const SEARCH_SET_SEARCH_VALUE = 'SEARCH_SET_SEARCH_VALUE';